### ISSUE TITLE
Remove asterisk from sample_name in sample data sheets

### ISSUE THREAD

**Issue by lukenoaa** [NOAA-Omics/noaa-omics-templates#8]
Suggest changing "*sample_name" to "sample_name". Having an asterisk in a table header feels wrong. If it's absolutely required by MIxS/NCBI, maybe we could add it back later.

**Comment by ksilnoaa** [comment]
This was fixed in v1.0.2 of the templates: https://docs.google.com/spreadsheets/d/1YBXFU9PuMqm7IT1tp0LTxQ1v2j0tlCWFnhSpy-EBwPw/edit?usp=sharing

If a project is using an old version of the templates it may not be up to date.
