### ISSUE TITLE
Example text

### ISSUE THREAD

**Issue by lukenoaa** [NOAA-Omics/noaa-omics-templates#9]
Some ideas to make the example text a little clearer -- on each sheet:
* Remove any example text from below the header row
* Add example text (if it's not there) to the row above the header row
* Use the same example study data for each sheet (eg, the example has "gomecc4" for sample data and "seamap" for study data)

**Comment by ksilnoaa** [comment]
In v1.0.8, bullet points 1 and 2 have been addressed. I agree it would be good to have consistent example text through-out, will close this when that has been added.

**Comment by lukenoaa** [comment]
Closing as issue is address in v1.0.8 and FAIR eDNA templates.
